# .prettierrc.yml
# see: https://prettier.io/docs/en/options.html
printWidth: 100
tabWidth: 2
semi: true
useTabs: false
singleQuote: true
trailingComma: all
bracketSpacing: true
jsxBracketSameLine: true
arrowParens: always
proseWrap: always